version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root1234!!
      MYSQL_DATABASE: sparta
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234!!
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6380:6379"

  common-module:
    image: common-image
    container_name: common-module-container
    ports:
      - "8080:8080"

  redis-module:
    image: redis-image
    container_name: redis-module-container
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - common-module
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  user-module:
    image: user-image
    container_name: user-module-container
    ports:
      - "8084:8080"
    depends_on:
      - mysql
      - common-module
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/sparta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!!

  coupon-module:
    image: coupon-image
    container_name: coupon-module-container
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - redis
      - common-module
      - redis-module
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/sparta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!!

  issue-coupon-module:
    image: issue-coupon-image
    container_name: issue-coupon-module-container
    ports:
      - "8083:8080"
    depends_on:
      - mysql
      - redis
      - common-module
      - redis-module
      - coupon-module
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/sparta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!!
